[project]
name = "andreuxmath-github-io"
version = "0.1.0"
description = "Personal website project, built with mkdocs"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.1",
]
